name: PPOPT
channels:
  - conda-forge
  - defaults
  - http://conda.anaconda.org/gurobi
dependencies:
  - numpy
  - matplotlib
  - scipy
  - numba
  - pytest
  - setuptools
  - psutil
  - pathos
  - plotly
  - cvxopt
  - quadprog
  - python=3.7
  - pip:
    - gurobipy
    - pypoman
